version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laraveluser
            DB_PASSWORD: secretpassword
        command: php artisan serve --host=0.0.0.0 --port=8000
    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: secretpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
